const techs = [
  { id: 0, name: "React", url: "https://reactjs.org/", description: "A JavaScript library for UIs." },
  { id: 1, name: "Vue.js", url: "https://vuejs.org/", description: "The Progressive JavaScript Framework." },
  { id: 2, name: "Angular", url: "https://angular.io/", description: "Platform for building web apps." },
  { id: 3, name: "Node.js", url: "https://nodejs.org/", description: "JavaScript runtime built on V8." },
  { id: 4, name: "Django", url: "https://www.djangoproject.com/", description: "A high-level Python Web framework." },
  { id: 5, name: "Flask", url: "https://palletsprojects.com/p/flask/", description: "A lightweight WSGI web framework." },
  { id: 6, name: "Ruby Rails", url: "https://rubyonrails.org/", description: "A server-side web app framework." },
  { id: 7, name: "Laravel", url: "https://laravel.com/", description: "A PHP framework for web artisans." },
  { id: 8, name: "Spring Boot", url: "https://spring.io/projects/spring-boot", description: "Framework for stand-alone apps." },
  { id: 9, name: "TensorFlow", url: "https://www.tensorflow.org/", description: "An end-to-end open source ML platform." },
  { id: 10, name: "Express", url: "https://expressjs.com/", description: "Fast, unopinionated web framework for Node.js." },
  { id: 11, name: "Bootstrap", url: "https://getbootstrap.com/", description: "Popular HTML, CSS, and JS library." },
  { id: 12, name: "Tailwind", url: "https://tailwindcss.com/", description: "A utility-first CSS framework." },
  { id: 13, name: "Sass", url: "https://sass-lang.com/", description: "CSS preprocessor with superpowers." },
  { id: 14, name: "Redux", url: "https://redux.js.org/", description: "State management library for JS apps." },
  { id: 15, name: "MongoDB", url: "https://www.mongodb.com/", description: "The database for modern applications." },
  { id: 16, name: "PostgreSQL", url: "https://www.postgresql.org/", description: "Powerful, open source object-relational database system." },
  { id: 17, name: "MySQL", url: "https://www.mysql.com/", description: "One of the world's most popular relational database systems." },
  { id: 18, name: "Docker", url: "https://www.docker.com/", description: "Platform for developing and running applications." },
  { id: 19, name: "Kubernetes", url: "https://kubernetes.io/", description: "Automated container deployment, scaling, and management." },
  { id: 20, name: "Azure", url: "https://azure.microsoft.com/", description: "Cloud computing service created by Microsoft." },
  { id: 21, name: "AWS", url: "https://aws.amazon.com/", description: "Secure cloud services platform by Amazon." },
  { id: 22, name: "GCP", url: "https://cloud.google.com/", description: "Google Cloud Platform offers cloud computing services." },
  { id: 23, name: "Git", url: "https://git-scm.com/", description: "Distributed version control system." },
  { id: 24, name: "GitHub", url: "https://github.com/", description: "Web-based version control and collaboration platform for software developers." },
  { id: 25, name: "GitLab", url: "https://about.gitlab.com/", description: "Open-source tool for managing Git repositories." },
  { id: 26, name: "SVN", url: "https://subversion.apache.org/", description: "Centralized version control system known as Subversion." },
  { id: 27, name: "Jenkins", url: "https://www.jenkins.io/", description: "Open-source automation server for building, testing, and deploying software." },
  { id: 28, name: "JIRA", url: "https://www.atlassian.com/software/jira", description: "Issue and project tracking tool for teams." },
  { id: 29, name: "Confluence", url: "https://www.atlassian.com/software/confluence", description: "Content collaboration tool used to help teams collaborate and share knowledge efficiently." },
  { id: 30, name: "Pandas", url: "https://pandas.pydata.org/", description: "Data analysis and manipulation tool for Python." },
  { id: 31, name: "NumPy", url: "https://numpy.org/", description: "Fundamental package for scientific computing with Python." },
  { id: 32, name: "Tensor", url: "https://www.tensorflow.org/", description: "Machine Learning library for numerical computation using data flow graphs." },
  { id: 33, name: "PyTorch", url: "https://pytorch.org/", description: "An open source machine learning framework that accelerates the path from research prototyping to production deployment." },
  { id: 34, name: "Scikit-learn", url: "https://scikit-learn.org/stable/", description: "Machine learning library for the Python programming language." },
  { id: 35, name: "Matplotlib", url: "https://matplotlib.org/", description: "Plotting library for the Python programming language and its numerical mathematics extension NumPy." },
  { id: 36, name: "Seaborn", url: "https://seaborn.pydata.org/", description: "Python visualization library based on matplotlib providing a high-level interface for drawing attractive statistical graphics." },
  { id: 37, name: "Plotly", url: "https://plotly.com/", description: "Graphing library for making interactive, publication-quality graphs online." },
  { id: 38, name: "D3.js", url: "https://d3js.org/", description: "JavaScript library for producing dynamic, interactive data visualizations in web browsers." },
  { id: 39, name: "Tableau", url: "https://www.tableau.com/", description: "Interactive data visualization software company." },
  { id: 40, name: "Power BI", url: "https://powerbi.microsoft.com/", description: "Business analytics service by Microsoft." },
  { id: 41, name: "Looker", url: "https://looker.com/", description: "Business intelligence software and big data analytics platform." },
  { id: 42, name: "Snowflake", url: "https://www.snowflake.com/", description: "Cloud-based data warehousing company." },
  { id: 43, name: "Airflow", url: "https://airflow.apache.org/", description: "Platform to programmatically author, schedule, and monitor workflows." },
  { id: 44, name: "Luigi", url: "https://github.com/spotify/luigi", description: "Python module that helps you build complex pipelines of batch jobs." },
  { id: 45, name: "Kafka", url: "https://kafka.apache.org/", description: "Open-source stream-processing software platform." },
  { id: 46, name: "RabbitMQ", url: "https://www.rabbitmq.com/", description: "Open-source message-broker software." },
  { id: 47, name: "ActiveMQ", url: "http://activemq.apache.org/", description: "Open-source multi-protocol messaging broker." },
  { id: 48, name: "Redis", url: "https://redis.io/", description: "In-memory data structure store, used as a database, cache, and message broker." },
  { id: 49, name: "Memcached", url: "https://memcached.org/", description: "General-purpose distributed memory caching system." },
  { id: 50, name: "Elasticsearch", url: "https://www.elastic.co/elasticsearch/", description: "Search and analytics engine." },
  { id: 51, name: "Solr", url: "https://lucene.apache.org/solr/", description: "Open-source search platform built on Apache Lucene." },
  { id: 52, name: "Splunk", url: "https://www.splunk.com/", description: "Software for searching, monitoring, and analyzing machine-generated big data." },
  { id: 53, name: "Logstash", url: "https://www.elastic.co/logstash", description: "Server-side data processing pipeline that ingests data from multiple sources simultaneously." },
  { id: 54, name: "Kibana", url: "https://www.elastic.co/kibana", description: "Data visualization dashboard for Elasticsearch." },
  { id: 55, name: "Grafana", url: "https://grafana.com/", description: "Open-source platform for monitoring and observability." },
  { id: 56, name: "Prometheus", url: "https://prometheus.io/", description: "Open-source monitoring system with a dimensional data model." },
  { id: 57, name: "New Relic", url: "https://newrelic.com/", description: "Observability platform built to help engineers create more perfect software." },
  { id: 58, name: "DataDog", url: "https://www.datadoghq.com/", description: "Monitoring service for cloud-scale applications." },
  { id: 59, name: "AppDynamics", url: "https://www.appdynamics.com/", description: "Application performance management and IT Operations Analytics company." },
  { id: 60, name: "Sentry", url: "https://sentry.io/", description: "Application monitoring and error tracking software." },
  { id: 61, name: "Rollbar", url: "https://rollbar.com/", description: "Error tracking software for developers." },
  { id: 62, name: "Raygun", url: "https://raygun.com/", description: "Software Intelligence platform for error monitoring, crash reporting." },
  { id: 63, name: "Dynatrace", url: "https://www.dynatrace.com/", description: "Software intelligence company providing application performance management." },
  { id: 64, name: "Nagios", url: "https://www.nagios.org/", description: "Open-source computer-software application that monitors systems, networks, and infrastructure." },
  { id: 65, name: "Zabbix", url: "https://www.zabbix.com/", description: "Enterprise-class open source distributed monitoring solution." },
  { id: 66, name: "InfluxDB", url: "https://www.influxdata.com/", description: "Open-source time series database." },
  { id: 67, name: "TimescaleDB", url: "https://www.timescale.com/", description: "Open-source time-series SQL database." },
  { id: 68, name: "Gitea", url: "https://gitea.io/", description: "Community-managed lightweight code hosting solution." },
  { id: 69, name: "Phabricator", url: "https://www.phacility.com/phabricator/", description: "Suite of open source tools for peer code review." },
  { id: 70, name: "Bitbucket", url: "https://bitbucket.org/", description: "Git repository management, code reviews, issue tracking." },
  { id: 71, name: "Sourcetree", url: "https://www.sourcetreeapp.com/", description: "Free Git client for Windows and Mac." },
  { id: 72, name: "GitKraken", url: "https://www.gitkraken.com/", description: "Cross-platform Git client with efficiency." },
  { id: 73, name: "Sublime Text", url: "https://www.sublimetext.com/", description: "A sophisticated text editor for code, markup, and prose." },
  { id: 74, name: "VS Code", url: "https://code.visualstudio.com/", description: "Free source-code editor made by Microsoft." },
  { id: 75, name: "Atom", url: "https://atom.io/", description: "Open-source text and source code editor." },
  { id: 76, name: "IntelliJ IDEA", url: "https://www.jetbrains.com/idea/", description: "Integrated development environment written in Java." },
  { id: 77, name: "PyCharm", url: "https://www.jetbrains.com/pycharm/", description: "Integrated development environment used for programming in Python." },
  { id: 78, name: "WebStorm", url: "https://www.jetbrains.com/webstorm/", description: "Integrated development environment for JavaScript." },
  { id: 79, name: "RubyMine", url: "https://www.jetbrains.com/ruby/", description: "A dedicated Ruby and Rails IDE." },
  { id: 80, name: "PhpStorm", url: "https://www.jetbrains.com/phpstorm/", description: "IDE for PHP and web developers." },
  { id: 81, name: "GoLand", url: "https://www.jetbrains.com/go/", description: "IDE by JetBrains aimed at providing an ergonomic environment for Go development." },
  { id: 82, name: "RStudio", url: "https://rstudio.com/", description: "Integrated development environment for R." },
  { id: 83, name: "Anaconda", url: "https://www.anaconda.com/", description: "Distribution of the Python and R programming languages for scientific computing." },
  { id: 84, name: "Miniconda", url: "https://docs.conda.io/en/latest/miniconda.html", description: "Minimal installer for conda." },
  { id: 85, name: "Jupyter", url: "https://jupyter.org/", description: "Open-source web application to create and share documents with live code." },
  { id: 86, name: "Zeppelin", url: "https://zeppelin.apache.org/", description: "Web-based notebook that enables data-driven, interactive data analytics." },
  { id: 87, name: "Spyder", url: "https://www.spyder-ide.org/", description: "Open-source IDE for Python with advanced editing, interactive testing, and debugging." },
  { id: 88, name: "NetBeans", url: "https://netbeans.apache.org/", description: "Integrated development environment for Java." },
  { id: 89, name: "Eclipse", url: "https://www.eclipse.org/", description: "IDE used in computer programming, and the most widely used Java IDE." },
  { id: 90, name: "Xcode", url: "https://developer.apple.com/xcode/", description: "IDE for macOS containing a suite of software development tools developed by Apple." },
  { id: 91, name: "Android Studio", url: "https://developer.android.com/studio", description: "The official IDE for Android app development." },
  { id: 92, name: "Visual Studio", url: "https://visualstudio.microsoft.com/", description: "IDE from Microsoft." },
  { id: 93, name: "Unity", url: "https://unity.com/", description: "Cross-platform game engine developed by Unity Technologies." },
  { id: 94, name: "Unreal Engine", url: "https://www.unrealengine.com/", description: "A powerful, real-time 3D creation platform." },
  { id: 95, name: "Godot", url: "https://godotengine.org/", description: "Open-source game engine for 2D and 3D games." },
  { id: 96, name: "Blender", url: "https://www.blender.org/", description: "Free and open-source 3D creation suite." },
  { id: 97, name: "Sketch", url: "https://www.sketch.com/", description: "Design toolkit built to help you create your best work." },
  { id: 98, name: "Figma", url: "https://www.figma.com/", description: "Interface design application that runs in the browser." },
  { id: 99, name: "Adobe XD", url: "https://www.adobe.com/products/xd.html", description: "Vector-based user experience design tool." },
];

export default techs;
