const techs = [
  {
    id: 0,
    name: "React",
    url: "https://reactjs.org/",
    description: "A JavaScript library for building user interfaces.",
    tags: ["frontend", "library", "UI"],
  },
  {
    id: 1,
    name: "Node.js",
    url: "https://nodejs.org/",
    description: "A JavaScript runtime built on Chrome's V8 JavaScript engine.",
    tags: ["backend", "runtime", "JavaScript"],
  },
  {
    id: 2,
    name: "Express",
    url: "https://expressjs.com/",
    description: "Fast, unopinionated, minimalist web framework for Node.js.",
    tags: ["backend", "framework", "Node.js"],
  },
  {
    id: 3,
    name: "Vue.js",
    url: "https://vuejs.org/",
    description: "The Progressive JavaScript Framework.",
    tags: ["frontend", "framework", "UI"],
  },
  {
    id: 4,
    name: "Angular",
    url: "https://angular.io/",
    description: "A platform and framework for building single-page client applications using HTML and TypeScript.",
    tags: ["frontend", "framework", "TypeScript"],
  },
  {
    id: 5,
    name: "Bootstrap",
    url: "https://getbootstrap.com/",
    description: "The most popular HTML, CSS, and JS library in the world.",
    tags: ["frontend", "CSS", "framework"],
  },
  {
    id: 6,
    name: "Tailwind CSS",
    url: "https://tailwindcss.com/",
    description: "A utility-first CSS framework for rapidly building custom designs.",
    tags: ["frontend", "CSS", "framework"],
  },
  {
    id: 7,
    name: "Sass",
    url: "https://sass-lang.com/",
    description: "A preprocessor scripting language that is interpreted or compiled into CSS.",
    tags: ["frontend", "CSS", "preprocessor"],
  },
  {
    id: 8,
    name: "MongoDB",
    url: "https://www.mongodb.com/",
    description: "The database for modern applications.",
    tags: ["database", "NoSQL", "backend"],
  },
  {
    id: 9,
    name: "PostgreSQL",
    url: "https://www.postgresql.org/",
    description: "The world's most advanced open source relational database.",
    tags: ["database", "SQL", "backend"],
  },
  {
    id: 10,
    name: "Redis",
    url: "https://redis.io/",
    description: "An open source (BSD licensed), in-memory data structure store, used as a database, cache, and message broker.",
    tags: ["database", "cache", "NoSQL"],
  },
  {
    id: 11,
    name: "Git",
    url: "https://git-scm.com/",
    description: "A free and open source distributed version control system.",
    tags: ["version control", "tool", "development"],
  },
  {
    id: 12,
    name: "Docker",
    url: "https://www.docker.com/",
    description: "Empowering App Development for Developers.",
    tags: ["containerization", "devops", "tool"],
  },
  {
    id: 13,
    name: "Kubernetes",
    url: "https://kubernetes.io/",
    description: "An open-source system for automating deployment, scaling, and management of containerized applications.",
    tags: ["containerization", "devops", "orchestration"],
  },
  {
    id: 14,
    name: "Webpack",
    url: "https://webpack.js.org/",
    description: "A bundler for JavaScript and friends.",
    tags: ["module bundler", "frontend", "tool"],
  },
  {
    id: 15,
    name: "Babel",
    url: "https://babeljs.io/",
    description: "A JavaScript compiler.",
    tags: ["compiler", "frontend", "JavaScript"],
  },
  {
    id: 16,
    name: "Jest",
    url: "https://jestjs.io/",
    description: "Delightful JavaScript Testing.",
    tags: ["testing", "frontend", "JavaScript"],
  },
  {
    id: 17,
    name: "Mocha",
    url: "https://mochajs.org/",
    description: "A feature-rich JavaScript test framework running on Node.js and in the browser, making asynchronous testing simple and fun.",
    tags: ["testing", "backend", "JavaScript"]
  }
];

export default techs;
